[WIP] Implemented: find screen for pre-order catalog (#85zryakpq)
hotwax/preorder pull request #119
Opened 2023-04-27 12:15 UTC by k2maan

### Related Issues

Closes #118 

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

2023-05-03 12:09 UTC, ymaheshwari1 requested changes

2023-05-03 12:09 UTC, ymaheshwari1 commented on src/store/modules/product/actions.ts
> +      commit(types.PRODUCT_CATALOG_UPDATED, { items, total: resp.data.response.numFound ? resp.data.response.numFound : 0 });
Handle the case when resp contains an error field.

2023-05-03 12:14 UTC, adityasharma7 requested changes

2023-05-04 06:20 UTC, k2maan commented on src/views/catalog.vue
> +            <ion-label>{{ prodCatalogCategoryTypeId === 'PCCT_PREORDR' ? $t('Pre-order') : $t('Back-order') }}</ion-label>
Updated sir

2023-05-04 07:15 UTC, adityasharma7 approved these changes

2023-05-04 07:15 UTC, merged