Implemented: computation jobs section on catalog page (#85zt0m698)
hotwax/preorder pull request #122
Opened 2023-05-08 09:37 UTC by k2maan

### Related Issues

Closes #118 

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

![computation job](https://user-images.githubusercontent.com/59442907/236790546-fe33defd-5651-44ce-95fc-d4e580f6919b.png)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

2023-05-08 12:08 UTC, ymaheshwari1 requested changes

2023-05-08 12:08 UTC, ymaheshwari1 commented on src/views/catalog.vue
> +          <ion-chip v-if="product.prodCatalogCategoryTypeIds.includes('PCCT_PREORDR') || product.prodCatalogCategoryTypeIds.includes('PCCT_PREORDR')" class="tablet" outline>
Update type for back-order

2023-05-08 12:08 UTC, ymaheshwari1 commented on src/views/catalog.vue
> +          // fetching statusId as well as only one fiel cannot be sent
```suggestion
          // fetching statusId as well as only one field cannot be sent
```

2023-05-08 12:26 UTC, k2maan commented on src/views/catalog.vue
> +          <ion-chip v-if="product.prodCatalogCategoryTypeIds.includes('PCCT_PREORDR') || product.prodCatalogCategoryTypeIds.includes('PCCT_PREORDR')" class="tablet" outline>
Fixed sir

2023-05-08 13:24 UTC, k2maan commented on src/views/catalog.vue
> +        showToast(translate("Something went wrong"));
Skipped sir

2023-05-08 13:24 UTC, k2maan commented on src/views/catalog.vue
> +            "shopId_fld1_op": "empty",
Updated

2023-05-09 10:07 UTC, adityasharma7 approved these changes

2023-05-09 10:07 UTC, merged