Implemented: button to copy audit message (#182)
hotwax/preorder pull request #185
Opened 2023-08-04 07:29 UTC by k2maan

### Related Issues

Closes #182 

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

2023-08-09 08:55 UTC, ymaheshwari1 requested changes

2023-08-09 08:55 UTC, ymaheshwari1 commented on src/views/catalog-product-details.vue
> +              <ion-button v-if="poSummary.header || poSummary.body" color="medium" fill="clear" slot="end" @click="copyAuditMsg()">
Import ion-button component

2023-08-10 05:05 UTC, k2maan commented on src/views/catalog-product-details.vue
> +              <ion-button v-if="poSummary.header || poSummary.body" color="medium" fill="clear" slot="end" @click="copyAuditMsg()">
Updated sir

2023-08-10 12:20 UTC, ymaheshwari1 approved these changes

2023-08-10 13:37 UTC, merged