Implemented: Job's time difference from next scheduled time in the Product Detail Page in timeline section (#192)
hotwax/preorder pull request #193
Opened 2023-08-10 09:03 UTC by sanskar345

### Related Issues

Closes #192

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

![new11](https://github.com/hotwax/preorder/assets/67117461/2005cb1c-899f-4a28-88c7-885e0a27deac)
![222222](https://github.com/hotwax/preorder/assets/67117461/404fc4ef-bd03-4f7a-87fe-0285912f3180)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

2023-08-10 12:56 UTC, ymaheshwari1 requested changes

2023-08-10 12:56 UTC, ymaheshwari1 commented on src/views/catalog-product-details.vue
> +          if(this.timeTillJob(presellingJob.runTime)?.includes('in')){
Find some other way to identify the past time.
Also check with @Dhiraj1405 for specific messages in the two cases.

2023-08-14 09:23 UTC, sanskar345 commented
@ymaheshwari1 changes are done please review.

2023-08-18 07:21 UTC, k2maan approved these changes

2023-08-21 06:04 UTC, ymaheshwari1 requested changes

2023-08-21 06:04 UTC, ymaheshwari1 commented on src/views/catalog-product-details.vue
> +    isTimePassed(time: number) {
Improve the naming for method.

2023-08-28 08:54 UTC, ymaheshwari1 approved these changes

2023-09-05 09:08 UTC, merged