Preorder/#187
hotwax/preorder pull request #230
Opened 2023-09-18 09:07 UTC by tanishqueSharma

### Related Issues

Closes #187

### Short Description and Why It's Useful

Changed the title of the catalog's product detail page form "Product summary" to "Product Audit".

### Screenshots of Visual Changes before/after (If There Are Any)

Before
![Screenshot (21)](https://github.com/hotwax/preorder/assets/142586530/d5eab861-2485-46ba-9b6c-aa8ada310449)

After
![Screenshot (22)](https://github.com/hotwax/preorder/assets/142586530/ffb8796b-65a2-4bf5-8dd2-0ba043e1cc99)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

2023-09-18 09:26 UTC, amansinghbais approved these changes

2023-09-18 09:29 UTC, ymaheshwari1 requested changes

2023-09-18 09:29 UTC, ymaheshwari1 commented on package-lock.json
> +    "node_modules/@vue/cli-plugin-unit-jest/node_modules/is-wsl": {
Revert the changes in package-lock file, as we don't push lock file until we have made some changes in the package.json file.

2023-09-18 10:26 UTC, ymaheshwari1 approved these changes

2023-09-20 12:49 UTC, k2maan requested changes

2023-09-20 12:49 UTC, k2maan commented on src/i18n/locales/en.json
>      "Product summary": "Product summary",
We should remove this entry and re-add the '"Product details' entry as we are using it on the product details page.

2023-09-20 13:06 UTC, k2maan approved these changes

2023-10-06 10:45 UTC, merged