#3bdgrp
hotwax/preorder pull request #25
Opened 2021-11-16 13:31 UTC by Yashi002

2021-11-18 05:07 UTC, ymaheshwari1 commented on src/views/update-password.vue
> +      return {
Please make the indentation consistent

2021-11-26 09:32 UTC, dt2patel commented on src/views/update-password.vue
> +  width: 375px;
change to max width

2021-11-26 09:33 UTC, dt2patel requested changes

2021-11-26 09:33 UTC, dt2patel commented on src/views/update-password.vue
> +.flex {
unused class

2021-12-10 10:55 UTC, ymaheshwari1 requested changes

2021-12-10 10:55 UTC, ymaheshwari1 commented on src/services/UserService.ts
> +  return client({
Why we have used client() here and not api()?

2022-01-24 07:08 UTC, closed without merging

2022-01-24 07:22 UTC, Yashi002 commented
Closed this PR, as branch can't be found

2022-01-24 07:32 UTC, Yashi002 commented on src/views/update-password.vue
> +      return {
Done

2022-01-24 07:32 UTC, Yashi002 commented on src/views/update-password.vue
> +  width: 375px;
Done