Improved: code to prepare loader on app mounted (#1x68xu9)
hotwax/preorder pull request #29
Opened 2021-12-27 10:10 UTC by Yashi002

2021-12-27 11:15 UTC, ymaheshwari1 requested changes

2021-12-28 05:32 UTC, Yashi002 commented on src/App.vue
> -    emitter.on('timeZoneDifferent', this.timeZoneDifferentAlert);
Updated Changes, added it back.

2021-12-28 05:32 UTC, Yashi002 commented on src/App.vue
> -    emitter.off('timeZoneDifferent', this.timeZoneDifferentAlert);
It wasn't required to be removed, added back

2021-12-28 11:29 UTC, ymaheshwari1 approved these changes
LGTM

2022-01-05 06:17 UTC, adityasharma7 approved these changes

2022-01-05 06:17 UTC, merged