Implemented logic for single sign-on(#1xx0wm1)
hotwax/preorder pull request #36
Opened 2022-01-05 12:08 UTC by disha1202

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

2022-01-10 04:30 UTC, ymaheshwari1 requested changes
Add changelog entry.

2022-01-10 04:30 UTC, ymaheshwari1 commented on src/views/login.vue
> +    console.log(this.$route);
Remove console statement

2022-01-10 04:30 UTC, ymaheshwari1 commented on src/views/login.vue
> +      console.log(this.$route.redirectedFrom?.query.info)
Remove console statement.

2022-01-10 06:39 UTC, disha1202 commented
> Add changelog entry.

Added changelog entry.

2022-01-10 06:39 UTC, disha1202 commented on src/views/login.vue
> +      console.log(this.$route.redirectedFrom?.query.info)
Removed.

2022-01-10 06:39 UTC, disha1202 commented on src/views/login.vue
> +    console.log(this.$route);
Removed.

2023-02-02 12:51 UTC, k2maan commented
Closing. Will be handled later when we pickup the commerce hub.

2023-02-02 12:51 UTC, closed without merging