Implemented code to display current OMS information on settings page(…
hotwax/preorder pull request #40
Opened 2022-01-10 10:43 UTC by disha1202

…#1y2ract)

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

2022-01-10 12:06 UTC, ymaheshwari1 requested changes

2022-01-10 12:06 UTC, ymaheshwari1 commented on src/views/settings.vue
> +        <ion-label>OMS</ion-label>
Internationalize the text.

2022-01-11 06:39 UTC, disha1202 commented on src/views/settings.vue
> +        <ion-label>OMS</ion-label>
Done.

2022-01-11 07:08 UTC, ymaheshwari1 approved these changes

2022-01-11 09:47 UTC, adityasharma7 approved these changes

2022-01-11 09:47 UTC, adityasharma7 commented on src/views/settings.vue
> +        <ion-note slot="end">{{instanceUrl}}</ion-note>
```suggestion
        <ion-note slot="end">{{ instanceUrl }}</ion-note>
```

2022-01-11 09:47 UTC, merged