Implemented: Feature to update password when receive requirePasswordChange with login API(#3bdgrp)
hotwax/preorder pull request #71
Opened 2022-07-18 13:08 UTC by shashwatbangar

### Related Issues

Closes #84 
https://github.com/hotwax/preorder/commit/47c54de6f56b84b0a4ca7c1c8b479d1568e37961

### Short Description and Why It's Useful

Suppose user login for first time, we give him a default password, then he/she needs to set his own password so account can stay secure.

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

2022-07-22 12:44 UTC, rathoreprashant commented on src/views/update-password.vue
> +            ...form,
indentation issue

2022-07-22 12:45 UTC, rathoreprashant commented on src/views/login.vue
> +        }
unwanted indentation

2022-07-22 13:47 UTC, shashwatbangar commented on src/views/update-password.vue
> +            ...form,
FIXED IT SIR.

2022-07-22 13:49 UTC, shashwatbangar commented on src/views/login.vue
> +        }
Fixed it.

2022-07-26 09:25 UTC, rathoreprashant commented on src/services/UserService.ts
> +    baseURL: process.env.VUE_APP_BASE_URL,
baseURL should be handled if .env has not VUE_APP_BASE_URL

2022-09-14 11:53 UTC, disha1202 requested changes

2022-09-14 11:53 UTC, disha1202 commented on src/store/modules/user/actions.ts
> +          showToast(translate('Your password expired. Please update your password.'));
Add static text in en.json file

2022-09-14 12:54 UTC, shashwatbangar commented on src/store/modules/user/actions.ts
> +          showToast(translate('Your password expired. Please update your password.'));
Done ma'am!

2023-02-02 12:52 UTC, k2maan commented
Closing. Will be done from scratch later.

2023-02-02 12:52 UTC, closed without merging